spring:
  profiles: local
  datasource:
    platform: h2
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb
      username: sa
      password:
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
#https://github.com/jojoldu/blog-comments/issues/197
